### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'id'

### ISSUE THREAD

**Issue by Weldaku** [ayushgun/tickets#1]
Ignoring exception in on_button_click
Traceback (most recent call last):
  File "C:\Users\postv\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\postv\Desktop\reddit botje\tokens\daaggoe\gg\ticketbot\tickets-main\src\main.py", line 157, in on_button_click
    ticket_channel = await guild.create_text_channel(
  File "C:\Users\postv\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\guild.py", line 948, in create_text_channel
    data = await self._create_channel(name, overwrites, ChannelType.text, category, reason=reason, **options)
  File "C:\Users\postv\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\guild.py", line 844, in _create_channel
    'id': target.id
AttributeError: 'NoneType' object has no attribute 'id'

**Comment by Weldaku** [comment]
Nevermind
